-- Seed de 5 troqueles de prueba para Fase 1
-- Estos datos permiten probar la funcionalidad antes de importar el Excel completo

INSERT INTO public.prod_etiquetas_troqueles (
  codigo,
  carpeta_original,
  carpeta_path,
  forma,
  ancho_mm,
  alto_mm,
  diametro_mm,
  dimensiones_texto,
  especial,
  multiple,
  con_hendido,
  cliente,
  trabajo,
  estado,
  necesita_revision,
  notas,
  documentos
) VALUES
(
  '0001',
  'TROQ 0001 . mnv_ 100mm x 60mm',
  'C:\\Users\\USUARIO\\Downloads\\ETIQUETAS\\TROQUELES\\TROQUELES\\TROQUELES ETIQUETAS\\TROQ 0001 . mnv_ 100mm x 60mm',
  'rectangular',
  100,
  60,
  null,
  '100mm x 60mm',
  false,
  false,
  false,
  null,
  'mnv_',
  'activo',
  false,
  null,
  '[]'::jsonb
),
(
  '0006',
  'TROQ 0006 . mnv_ 50mm . REDONDO',
  'C:\\Users\\USUARIO\\Downloads\\ETIQUETAS\\TROQUELES\\TROQUELES\\TROQUELES ETIQUETAS\\TROQ 0006 . mnv_ 50mm . REDONDO',
  'redondo',
  50,
  null,
  50,
  '50mm',
  false,
  false,
  false,
  null,
  'mnv_',
  'activo',
  false,
  null,
  '[]'::jsonb
),
(
  '0089',
  'TROQ 0089 . mnv_ 80mm x 130mm . OVALADO',
  'C:\\Users\\USUARIO\\Downloads\\ETIQUETAS\\TROQUELES\\TROQUELES\\TROQUELES ETIQUETAS\\TROQ 0089 . mnv_ 80mm x 130mm . OVALADO',
  'ovalado',
  80,
  130,
  null,
  '80mm x 130mm',
  false,
  false,
  false,
  null,
  'mnv_',
  'activo',
  false,
  null,
  '[]'::jsonb
),
(
  '0119',
  'TROQ 0119 . mnv_ 42,5mm x 47mm . TRIANGULO',
  'C:\\Users\\USUARIO\\Downloads\\ETIQUETAS\\TROQUELES\\TROQUELES\\TROQUELES ETIQUETAS\\TROQ 0119 . mnv_ 42,5mm x 47mm . TRIANGULO',
  'triangulo',
  42.5,
  47,
  null,
  '42,5mm x 47mm',
  false,
  false,
  false,
  null,
  'mnv_',
  'activo',
  false,
  null,
  '[]'::jsonb
),
(
  '0157',
  'TROQ 0157 . mnv_ doble 65mm - TURRIS - TROQUEL MULTIPLE - ESPECIAL',
  'C:\\Users\\USUARIO\\Downloads\\ETIQUETAS\\TROQUELES\\TROQUELES\\TROQUELES ETIQUETAS\\TROQ 0157 . mnv_ doble 65mm - TURRIS - TROQUEL MULTIPLE - ESPECIAL',
  'multiple',
  65,
  null,
  null,
  '65mm',
  true,
  true,
  false,
  'TURRIS',
  'mnv_ doble',
  'activo',
  false,
  'ESPECIAL | MULTIPLE/DOBLE',
  '[]'::jsonb
)
ON CONFLICT (codigo) DO NOTHING;
