-- SUPERSEDED — aplicado como supabase/migrations/20260925160000_bloque15_stock_articulos_editar_datos.sql
-- (revisión Claude 25 sep + clear uds/bulto y audit notas/condición).
-- Conservar solo como rastro; no aplicar este archivo.
