-- =====================================================================
-- Migración: prod_etiquetas_troqueles
-- Descripción: Catálogo de troqueles de la máquina troqueladora de etiquetas
-- =====================================================================

create table if not exists public.prod_etiquetas_troqueles (
  id bigint generated by default as identity primary key,
  
  -- Identificación
  codigo text not null unique,
  carpeta_original text not null,
  carpeta_path text,
  
  -- Dimensiones y forma
  forma text,
  ancho_mm numeric,
  alto_mm numeric,
  diametro_mm numeric,
  dimensiones_texto text,
  
  -- Características especiales
  especial boolean default false,
  multiple boolean default false,
  con_hendido boolean default false,
  
  -- Cliente y trabajo
  cliente text,
  trabajo text,
  
  -- Estado y gestión
  estado text default 'activo',
  necesita_revision boolean default false,
  notas text,
  
  -- Documentos asociados (JSON array)
  documentos jsonb,
  
  -- Timestamps
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Índices para búsquedas frecuentes
create index if not exists prod_etiquetas_troqueles_codigo_idx 
  on public.prod_etiquetas_troqueles(codigo);

create index if not exists prod_etiquetas_troqueles_forma_idx 
  on public.prod_etiquetas_troqueles(forma);

create index if not exists prod_etiquetas_troqueles_cliente_idx 
  on public.prod_etiquetas_troqueles(cliente);

create index if not exists prod_etiquetas_troqueles_estado_idx 
  on public.prod_etiquetas_troqueles(estado);

create index if not exists prod_etiquetas_troqueles_necesita_revision_idx 
  on public.prod_etiquetas_troqueles(necesita_revision);

-- Trigger para actualizar updated_at
create or replace function public.update_prod_etiquetas_troqueles_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists prod_etiquetas_troqueles_updated_at_trigger 
  on public.prod_etiquetas_troqueles;

create trigger prod_etiquetas_troqueles_updated_at_trigger
  before update on public.prod_etiquetas_troqueles
  for each row
  execute function public.update_prod_etiquetas_troqueles_updated_at();

-- Row Level Security (RLS)
alter table public.prod_etiquetas_troqueles enable row level security;

-- Política de lectura: todos los usuarios autenticados pueden leer
create policy "prod_etiquetas_troqueles_select_policy"
  on public.prod_etiquetas_troqueles
  for select
  using (auth.role() = 'authenticated');

-- Política de inserción: todos los usuarios autenticados pueden insertar
create policy "prod_etiquetas_troqueles_insert_policy"
  on public.prod_etiquetas_troqueles
  for insert
  with check (auth.role() = 'authenticated');

-- Política de actualización: todos los usuarios autenticados pueden actualizar
create policy "prod_etiquetas_troqueles_update_policy"
  on public.prod_etiquetas_troqueles
  for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Política de eliminación: todos los usuarios autenticados pueden eliminar
create policy "prod_etiquetas_troqueles_delete_policy"
  on public.prod_etiquetas_troqueles
  for delete
  using (auth.role() = 'authenticated');

-- Comentarios en tabla y columnas
comment on table public.prod_etiquetas_troqueles is 
  'Catálogo de troqueles de la máquina troqueladora de etiquetas. Gestiona inventario, características y documentación asociada.';

comment on column public.prod_etiquetas_troqueles.codigo is 
  'Código del troquel normalizado a 4 dígitos (ej: 0001, 0157). Único.';

comment on column public.prod_etiquetas_troqueles.carpeta_original is 
  'Nombre original de la carpeta de donde se extrajo el troquel.';

comment on column public.prod_etiquetas_troqueles.forma is 
  'Forma del troquel: rectangular, redondo, ovalado, triangulo, hexagonal, multiple, especial, desconocida.';

comment on column public.prod_etiquetas_troqueles.ancho_mm is 
  'Ancho del troquel en milímetros.';

comment on column public.prod_etiquetas_troqueles.alto_mm is 
  'Alto del troquel en milímetros (para formas rectangulares/ovaladas).';

comment on column public.prod_etiquetas_troqueles.diametro_mm is 
  'Diámetro del troquel en milímetros (para formas redondas).';

comment on column public.prod_etiquetas_troqueles.dimensiones_texto is 
  'Representación textual de las dimensiones tal como aparecen en la carpeta original.';

comment on column public.prod_etiquetas_troqueles.especial is 
  'Indica si es un troquel especial (true) o estándar (false).';

comment on column public.prod_etiquetas_troqueles.multiple is 
  'Indica si es un troquel múltiple/doble (true) o simple (false).';

comment on column public.prod_etiquetas_troqueles.con_hendido is 
  'Indica si el troquel incluye hendido (true) o no (false).';

comment on column public.prod_etiquetas_troqueles.cliente is 
  'Nombre del cliente asociado al troquel (TURRIS, VINESTAR, etc).';

comment on column public.prod_etiquetas_troqueles.trabajo is 
  'Descripción del trabajo o proyecto asociado al troquel.';

comment on column public.prod_etiquetas_troqueles.estado is 
  'Estado actual del troquel: activo, vacio, mantenimiento, etc.';

comment on column public.prod_etiquetas_troqueles.necesita_revision is 
  'Indica si el troquel necesita revisión manual (datos incompletos, ambiguos, etc).';

comment on column public.prod_etiquetas_troqueles.notas is 
  'Notas adicionales sobre el troquel.';

comment on column public.prod_etiquetas_troqueles.documentos is 
  'Array JSON con metadatos de documentos asociados (nombre, tipo, extensión, bytes).';
